# Generated by Django 5.2 on 2025-05-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_rename_customerphone_roomusageorder_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Closed',
            field=models.BooleanField(default=False),
        ),
    ]
