# Generated by Django 5.2 on 2025-05-06 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_announcement_image_alter_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='ItemID',
        ),
        migrations.AlterField(
            model_name='productorder',
            name='OrderTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField(default=1)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.item')),
                ('ProductOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.productorder')),
            ],
        ),
        migrations.AddField(
            model_name='productorder',
            name='Items',
            field=models.ManyToManyField(through='management.OrderItem', to='management.item'),
        ),
    ]
