# Generated by Django 5.2.1 on 2025-05-11 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_roomcleaningorder_status_alter_productorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcleaningorder',
            name='StaffID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.staff'),
        ),
        migrations.AlterField(
            model_name='roomcleaningorder',
            name='Status',
            field=models.IntegerField(choices=[(1, '已完成'), (0, '未完成')], default=0),
        ),
    ]
