# Generated by Django 5.2 on 2025-05-05 19:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_staff_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomusageorder',
            old_name='CustomerPhone',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='roomusageorder',
            old_name='PlayDuration',
            new_name='DurationTime',
        ),
        migrations.RenameField(
            model_name='roomusageorder',
            old_name='PlayTime',
            new_name='EndTime',
        ),
        migrations.RenameField(
            model_name='roomusageorder',
            old_name='RoomID',
            new_name='Room',
        ),
        migrations.AddField(
            model_name='roomusageorder',
            name='StartTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customer',
            name='RoomUsageStatus',
            field=models.IntegerField(choices=[(2, '已预约'), (1, '正在使用'), (0, '未使用')], default=0),
        ),
    ]
