# Generated by Django 5.2 on 2025-05-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_room_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomusageorder',
            name='Status',
            field=models.IntegerField(choices=[(0, '未开始'), (0, '正在使用'), (1, '已结束'), (2, '已取消')], default=0),
        ),
    ]
