# Generated by Django 5.2 on 2025-05-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_announcement_image_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Disabled',
            field=models.BooleanField(default=False),
        ),
    ]
