# Generated by Django 5.2 on 2025-05-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_item_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
