# Generated by Django 5.2 on 2025-05-06 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_remove_productorder_itemid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='StaffID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.staff'),
        ),
    ]
