# Generated by Django 5.2 on 2025-05-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_productorder_staffid'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcleaningorder',
            name='Status',
            field=models.IntegerField(choices=[(1, '已送达'), (0, '未送达'), (2, '已取消')], default=0),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='Status',
            field=models.IntegerField(choices=[(1, '已送达'), (0, '未送达'), (2, '已取消')], default=0),
        ),
    ]
